import scriptSeriesMap from './generated/scriptSeriesMap.json';

import {
  SERIES_PREFIX_RULES,
  stripSeriesPrefixFromScriptId,
  type ScriptSeriesDir,
} from '../seriesRegistry.ts';

/** Which project under `video_ops/projects/` holds an episode. */
export type VideoOpsScriptSeries = ScriptSeriesDir;

/** Repo-relative disk root — absolute paths use `path.join(videoOpsRoot, VIDEO_OPS_PROJECTS_DIR, …)`. */
export const VIDEO_OPS_PROJECTS_DIR = 'projects';

/** @deprecated Use VIDEO_OPS_PROJECTS_DIR for disk paths. */
export const VIDEO_OPS_SCRIPTS_ROOT = VIDEO_OPS_PROJECTS_DIR;

/** Generated Turn LSP payloads (gitignored). Relative to Remotion publicDir (`projects/`). */
export const TURN_KNOWLEDGE_CACHE_REL = '.cache/turn-knowledge-cache';

/** Series that owns cross-episode Lean/Turn reference files. */
export const REFERENCE_SHARED_SERIES: ScriptSeriesDir = 'algebra';

/** Resolve series from script slug. Map is regenerated by `npm run sync` from projects/. */
export function videoOpsScriptSeries(scriptId: string): VideoOpsScriptSeries {
  const mapped = (scriptSeriesMap as Record<string, string>)[scriptId];
  if (mapped) {
    return mapped as VideoOpsScriptSeries;
  }
  for (const rule of SERIES_PREFIX_RULES) {
    if (scriptId.startsWith(rule.prefix)) {
      return rule.series;
    }
  }
  return 'algebra';
}

/** @deprecated Use videoOpsScriptSeries */
export function videoOpsScriptCollection(scriptId: string): VideoOpsScriptSeries {
  return videoOpsScriptSeries(scriptId);
}

/** Episode folder relative to Remotion publicDir (`projects/`). Used by staticFile(). */
export function videoOpsScriptFolder(scriptId: string): string {
  return `${videoOpsScriptSeries(scriptId)}/${scriptId}`;
}

/** Episode folder relative to video_ops root (includes `projects/`). Used for disk I/O. */
export function videoOpsScriptDiskFolder(scriptId: string): string {
  return `${VIDEO_OPS_PROJECTS_DIR}/${videoOpsScriptFolder(scriptId)}`;
}

/** `sets-v2-04-set-equality` → `04-set-equality` for animation.md / compile identity. */
export function canonicalVideoOpsScriptId(scriptId: string): string {
  const trimmed = scriptId.trim();
  return stripSeriesPrefixFromScriptId(trimmed) ?? trimmed;
}

export function videoOpsSeriesSharedFolder(series: VideoOpsScriptSeries): string {
  return `${series}/shared`;
}

export function videoOpsSharedReferencePath(relativeFile: string): string {
  const clean = relativeFile.replace(/^\/+/, '');
  return `${videoOpsSeriesSharedFolder(REFERENCE_SHARED_SERIES)}/reference/${clean}`;
}

/** Rendered MP4 output folder inside each script project. */
export const VIDEO_OPS_SCRIPT_EXPORT_DIR = 'export';

/** Per-platform publish copy (English + China groups). */
export const VIDEO_OPS_SOCIAL_POSTS_FILENAME = 'social-posts.json';

export function videoOpsScriptExportMp4RelativePath(scriptId: string): string {
  return `${videoOpsScriptFolder(scriptId)}/${VIDEO_OPS_SCRIPT_EXPORT_DIR}/video.mp4`;
}

export function videoOpsSocialPostsRelativePath(scriptId: string): string {
  return `${videoOpsScriptFolder(scriptId)}/${VIDEO_OPS_SOCIAL_POSTS_FILENAME}`;
}

export function turnKnowledgeCacheStaticPath(sourceFile: string | undefined, sourceHash: string): string {
  const safe = (sourceFile ?? 'inline').replace(/[@/]/g, '_');
  return `${TURN_KNOWLEDGE_CACHE_REL}/${safe}-${sourceHash}.json`;
}
